### ISSUE TITLE
Document importing of LLEAD

### ISSUE THREAD

**Issue by ayyubibrahimi** [ipno-llead/processing#333]
Hey @[huy-d-nguyen](https://github.com/huy-d-nguyen) question for you. What metadata do you need to import documents into LLEAD? There are currently two versions of the `post_officer_history.csv` tables, one that includes metadata and one that does not. Please advise as to what metadata your team needs to attach documents to an officer's profile. At the moment, this is the extent of the metadata that is produced by our processing pipeline. Is this sufficient for uploading onto LLEAD/what is sufficient?

[post_officer_history_w_metadata.csv](https://github.com/ppact/processing/files/9475360/post_officer_history_w_metadata.csv)
[post_officer_history_clean.csv](https://github.com/ppact/processing/files/9475362/post_officer_history_clean.csv)

**Comment by ayyubibrahimi** [comment]
cc: @rajivsinclair @lsukaristone

**Comment by huy-d-nguyen** [comment]
Hi @ayyubibrahimi , currently the fields in https://hub.wrgl.co/@ipno/r/data/refs/heads/documents are fine to us to import the documents. Is it ok to you?

**Comment by ayyubibrahimi** [comment]
Hey @huy-d-nguyen, at the moment, the documents table that we have in production does not include all of those fields. Do you know which of the fields are required for import? All? Some?

**Comment by huy-d-nguyen** [comment]
Hi @ayyubibrahimi , I think @rajivsinclair and @ @lsukaristone will know which fields are going to be used in future. Can you discuss more with them about that?

**Comment by ayyubibrahimi** [comment]
Sounds good. Thanks!

**Comment by ayyubibrahimi** [comment]
@rajivsinclair - Follow-up question re: the importation of POST officer history reports. Am I correct in appending these data to the events table, rather than the [post-officer-history](https://hub.wrgl.co/@ipno/r/data/refs/heads/post-officer-history) table on wrgl? Currently unsure as to 1) how the migration map is generated and 2) how this post officer history table will be used to generate the migration map moving forward.
