### ISSUE TITLE
Validation check

### ISSUE THREAD

**Issue by ayyubibrahimi** [ipno-llead/processing#448]
Hey @pckhoi just had a talk with Rajiv about `datavalid` and introducing new validation checks into the `gh_runner`  to validate foreign keys. More generally, the validation check should query the database, look at schema, and check if the new output is compatible.  Do you think that we could use `datavalid` to validate foreign keys? If not, do you have a sense of what is the best way to introduce this validation check? This is something the devs can build. Thanks!

**Comment by pckhoi** [comment]
Okay, please tell them to open an issue at https://github.com/pckhoi/datavalid to discuss the features and syntax.
